version: '3.8'

services:
  django:
    build: .
    container_name: art-den-back
    # command: gunicorn artden.wsgi:application --bind 0.0.0.0:$PORT
    # command: gunicorn --bind :8000 --workers 3 artden.wsgi:application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    container_name: artdendata
    environment:
      - POSTGRES_DB=artden
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
