# Generated by Django 3.2 on 2021-04-20 02:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, default='images/avatar/noavatardefault.jpeg', upload_to='images/avatars')),
                ('school', models.CharField(max_length=150)),
                ('graduation_year', models.PositiveSmallIntegerField()),
                ('personal_story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artwork_image', models.ImageField(blank=True, default='images/artworks/noImageAvailable.jpeg', upload_to='images/artworks')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pulication_date', models.DateField(blank=True, default=datetime.date.today)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='art.student')),
            ],
        ),
    ]
