# Generated by Django 3.2 on 2021-04-23 05:50

import art.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artwork_image', models.ImageField(blank=True, default='images/artworks/noImageAvailable.jpeg', upload_to='images/artworks')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('publication_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, default='images/avatars/noavatardefault.jpeg', upload_to='images/avatars')),
                ('school', models.CharField(max_length=150)),
                ('graduation_year', models.PositiveSmallIntegerField(default=art.models.current_year, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2030)])),
                ('personal_story', models.TextField()),
            ],
        ),
    ]
