# Generated by Django 3.2 on 2021-04-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='pulication_date',
            field=models.DateField(),
        ),
    ]
