# Generated by Django 3.2 on 2021-04-20 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/noavatardefault.jpeg', upload_to='images/avatars'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
