# Generated by Django 3.2 on 2021-04-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_artwork_pulication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='pulication_date',
        ),
    ]
