# Generated by Django 3.2 on 2021-04-19 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_remove_artwork_pulication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='pulication_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
