# Generated by Django 3.2 on 2021-04-20 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0003_alter_student_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_artworks', to='student_users.studentuser'),
            preserve_default=False,
        ),
    ]
