# Generated by Django 3.2 on 2021-04-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_artwork_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='pulication_date',
            new_name='publication_date',
        ),
    ]
