# Generated by Django 3.2 on 2021-04-24 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0005_rename_user_student_studentuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentuser_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
