# Generated by Django 3.2 on 2021-04-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_alter_student_studentuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(blank=True, default='images/artworks/noImageAvailable.jpeg', upload_to='https://the-art-den-backend.s3.amazonaws.com/media/'),
        ),
    ]
