# Generated by Django 3.2 on 2021-04-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_alter_artwork_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(blank=True, default='images/artworks/ImageAvailable.jpeg', upload_to='images/artworks'),
        ),
    ]
